### ISSUE TITLE
Documentation: how to generate a set of slides

### ISSUE THREAD

**Issue by mahiki** [kdheepak/TerminalUserInterfaces.jl#1]
I really enjoyed your juliacon presentation, it looks like this has great potential for creating tools to:

* present slides from a terminal based on text files
* make cool terminal UI for small applications

please include a folder with sample code to demonstrate how you made the presentation from juliacon2020.

[juliacon 2020: Terminal User Interfaces in Julia](https://live.juliacon.org/talk/SD8PSC)
[juliacon 2020: Terminal User Interfaces in Julia - YOUTUBE](https://www.youtube.com/watch?time_continue=10&v=-TASx67pphw&feature=emb_title)

**Comment by kdheepak** [comment]
I moved the issue here since it is more relevant to this repository. For the presentation at JuliaCon2020, all the code I used is located at this repository:

https://github.com/kdheepak/juliacon2020-terminal-user-interfaces-in-julia/

Currently, if you want to build something similar, you can look through the following links in this order:

1) https://kdheepak.com/TerminalUserInterfaces.jl/dev/usage/
2) https://github.com/kdheepak/TerminalUserInterfaces.jl/tree/master/examples
3) https://github.com/kdheepak/TerminalUserInterfaces.jl/tree/master/src/widgets
4) https://github.com/kdheepak/juliacon2020-terminal-user-interfaces-in-julia/blob/master/main.jl

The first shows you how to use this package. The second link has examples of widgets. The third is the link to the current list of widgets I've implemented. The last link is to the `main.jl` file I ran for the JuliaCon talk. It makes a slideshow for the presentation, where each slide is just a separate widget. It's a very custom implementation that I made just for the JuliaCon presentation, and I'm sharing it so that it can be instructive in how use TerminalUserInterfaces.jl. I don't imagine one will be able to use that `main.jl` file without any changes for a terminal presentation. 

In the past, I've toyed with the idea of making slides directly from a Markdown document. Here is an older effort where I experimented with this:

https://github.com/kdheepak/Presentation.jl

This will work well for simple content, but it does not support something more dynamic / with animations.

Hope that covers everything. Let me know if you have more questions!

**Comment by mahiki** [comment]
Perfect thanks!

Now I see this is included in repo [TerminalUserInterfaces.jl](https://github.com/kdheepak/TerminalUserInterfaces.jl)

Looks like the presentation is available too, excellent.
